### ISSUE TITLE
data-currency option not working for EURO

### ISSUE THREAD

**Issue by salsa-system** [qualiabyte/coinlens#2]
`<div class="coinlens bitcoin-price" data-currency="EUR"></div>` displays price in USD , not in EURO

**Comment by qualiabyte** [comment]
Thanks for reporting this! There was indeed a bug with using the `data-currency` setting for the price widget. Today I've made a [small change](https://github.com/qualiabyte/coinlens/commit/17e1ba87b0c7c1094ce24539680c0ef30beae471) which should resolve the issue, which is now included in version 0.0.6. Let me know how it goes if you get a chance to test it. ^_^

**Comment by salsa-system** [comment]
Quoting Tyler Florez <notifications@github.com>:

> Thanks for reporting this! There was indeed a bug with using the
> data-currency setting for the price widget. Today I've made a small
> change[1] which should resolve the issue, which is now included in
> version 0.0.6. Let me know how it goes if you get a chance to test it.
> ^_^
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[2], or mute the
thread[3].
>       

It's working great now...thx for the fix


Links:
------
[1]  
https://github.com/qualiabyte/coinlens/commit/17e1ba87b0c7c1094ce24539680c0ef30beae471
[2] https://github.com/qualiabyte/coinlens/issues/2#issuecomment-231913939
[3]  
https://github.com/notifications/unsubscribe/ALPfK81S2TFsxf5O3NxG7jl2ABFyhJLOks5qUu74gaJpZM4JIL95
