### ISSUE TITLE
Biteasy API no longer available

### ISSUE THREAD

**Issue by JanGross** [qualiabyte/coinlens#3]
The Biteasy API has been shut down on January 20th 2017*.  
So the balance history no longer works. 
* https://blog.biteasy.com/end-of-life

**Comment by blackshroud** [comment]
I too would like to see this updated to a new API for balance history

**Comment by JanGross** [comment]
I was looking into switching biteasy with the blockchain.info API   
since it has already been used for the balance info.  
Unfortunately their `rawaddr` endpoint does not support CORS   
and would require proxying the requests.   

What would be a viable alternative API?

**Comment by qualiabyte** [comment]
Hi @JanGross, thanks for reporting the issue!
Yes, it's always been a little tricky finding the right APIs.

It looks to me like the BlockCypher API can work as a good replacement.
In particular, their "Address Full Endpoint" resource seems to have the data we need.
https://www.blockcypher.com/dev/bitcoin/#address-full-endpoint

This evening I pushed a new version (0.0.7) with these changes: 7374a9c
It mainly replaces the calls to the BitEasy API.

Please let me know how this works for you, and if you have any thoughts.

**Comment by JanGross** [comment]
Applied the update, works just fine now. Thank you 👍
